### ISSUE TITLE
DXC Shader compiler pending issues

### ISSUE THREAD

**Issue by turanszkij** [turanszkij/WickedEngine#611]
- [ ] pack-optimized issue with tessellation shaders: https://github.com/microsoft/DirectXShaderCompiler/issues/3362
- [ ] Vulkan mesh shader compilation issue with templated load: https://github.com/microsoft/DirectXShaderCompiler/issues/4865
- [ ] Linux libncurses5 dependency: https://github.com/microsoft/DirectXShaderCompiler/issues/4892
- [ ] Spirv incorrectly assumes VK_FORMAT_R32G32B32A32_SFLOAT image format for RWTexture2D<float3>: https://github.com/microsoft/DirectXShaderCompiler/issues/4828
- [ ] NV extension generated incorrectly: https://github.com/microsoft/DirectXShaderCompiler/issues/6672
